#include<iostream>
using namespace std;
int main(){
    int arr[5] = {1, 2, 3, 4, 5};
    char ch[6] = "abcde";  // you have to take the array size is 1 greater than the content size... because it stores the null character there...

    // if we perform following operations..

    // ATTENTION HERE...
    cout << arr << endl;    // it will print the address...
    cout << ch << endl;     // it will print all the elements...
    // it will print untill it gets a null character at last...

    


    // if we take pointers...
    int* p = arr;
    char* r = ch;
    cout << p << endl;
    cout << r << endl;   // same this also print the elements untill it gets a null character...

    char tex = 'Q';
    char* reo = &tex;
    cout << reo << endl;   // it can print some extra characters...it will continue untill it finds a null character...



    char ch2[6] = "abcde";
    // this means initially "abcde" stored in a temporary memory and then transfered to the permanentn memory...
    // but in case of pointer...
    char* c = "abcde"; 
    // this means in "abcde" stored in temporary memory and a pointer named c is pointing to the address of 1st character...
    // which is risky, if the temporary memory is only read only memory....
    // it will store the current value...after initiallization it clears the previous value...

    // ** ATTENTION TO THE UPPER NOTE.... 




    return 0;
}
